version: '3.8'

services:
  minmax_octopus_bot:
    container_name: MinMaxOctopusBot
    image: eelmafia/octopus-minmax-bot
    restart: unless-stopped
    environment:
      - ACC_NUMBER=<your_account_number>
      - API_KEY=<your_api_key>
      - OCTOPUS_LOGIN_EMAIL=<your_email>
      - OCTOPUS_LOGIN_PASSWD=<your_password>
      - EXECUTION_TIME=23:00
      - DISCORD_WEBHOOK=<your_webhook_url>
      - ONE_OFF=false
      - DRY_RUN=false
      - PYTHONUNBUFFERED=1
      - TARIFFS=go,agile,flexible
